###COLORS###
WIDTH=1225
HEIGHT=960

SLV_WIDTH="1000"
SLV_HEIGHT="700"

SMALL_WIN_WIDTH="400"
SMALL_WIN_HEIGHT="300"

ERR_WIDTH=400
ERR_HEIGHT=250

PANEL_COLOR="#fff"
BG_COLOR="#fff"

###FONTS###
FONT_FAMILY="Helvetica"
FONT_SIZE=11
FONT_COLOR="#000000"

###ROWS###
LIMIT_COLOR="#ff0000"
HIGHLIGHT_COLOR="#646464"
UNACTIVE_COLOR="#ffffff"
###BUTTONS###
BUTTON_COLOR="#fff"
BUTTON_WIDTH=16
BUTTON_HEIGHT=2

ROWS_PAD=1
BD_SIZE=1


###PATHS###
APP_PATH="./"
BACKUPS_PATH="./backup/"
LOGS_PATH="./logs/std.log"
PLOTS_LOGS_PATH="./logs/plots.log"
COSM_PATH="./databases/cosm.txt"
CARN_PATH="./databases/carn.txt"
COSML_PATH="./databases/cosmlog.txt"
CARNL_PATH="./databases/carnlog.txt"
DB_PATH="./databases/"
BUFFERS_PATH="./buff/"
IMAGES_PATH="./Images/"